### ISSUE TITLE
Installation web is not working

### ISSUE THREAD

**Issue by beacamara** [segrelab/comets#45]
Hello! I am trying to download and install Comets in my computer, and the website 'http://www.runcomets.org/' is not working anymore. I would like to know if the program still works.

Thank you so much

Beatriz

**Comment by dukovski** [comment]
The issue as resolved. It should be OK now. Please let us know if there are any problems with the download. 

Thanks,
Ilija

**Comment by beacamara** [comment]
Thank you so much. Now is working perfectly
