### ISSUE TITLE
Fluxes variation analysis/optimization

### ISSUE THREAD

**Issue by zorzansi** [segrelab/comets#47]
Hi,
we are working on a project involving a microbial community, and we would like to find an optimal flux which remains feasible but maximizes a metabolite or a metabolite(s) class. Do you think that this can be implemented in Comets and how many CPU and RAM do you think such an optimization might require for a community of 6-12 species?

Thank you!

**Comment by dukovski** [comment]
Hi, 
Thanks for the interest. Yes, you can do that in comets. I am not sure what you mean by maximizes a metabolite. If you mean maximum production of a secreted metabolite, yes you can explore that by changing the exchange parameters and/or setting objective reactions that include the exchange reaction for the metabolite. In Comets, you can set the objective to be different than the biomass. 

For 6-12 species, in well mixed conditions (single spatial grid point) you can do it in practically any computer, including a laptop. If you do it in spatially structured environment, it takes few days to run 10000 steps for two models in 400x400 grid, running 8 threads in parallel. So you can easily do 6-12 species, if you run 100x100 spatial grid for 1000 time points, for example.   

I hope this helps. 

Ilija

**Comment by dukovski** [comment]
I am closing this.
