### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by liaochen1988** [segrelab/comets#48]
Happy new year! I am new to Comets. Does Comets enable Lexicographic optimization, where different objectives can be ranked and optimized sequentially? For example, we first maximize biomass production, then minimize acetate secretion, then minimize succinate secretion, etc. Currently, it seems that Comets implements biomass production maximization followed by minimization of  total flux. This is already very useful. It would be great if optimization can be more flexible for users.

**Comment by dukovski** [comment]
We do have implemented multiple optimizations. I don't have a manual entry for that yet. And we don't have cometspy support for that. If interested, please let me know, and we can implement it fully. Thanks!
