### ISSUE TITLE
Lexicographic optimization

### ISSUE THREAD

**Issue by liaochen1988** [segrelab/comets#49]
Happy new year! I am new to Comets. Does Comets enable lexicographic optimization, where different objectives can be ranked and optimized sequentially? For example, we first maximize biomass production, then minimize acetate secretion, then minimize succinate secretion, etc. Currently, it seems that Comets implements biomass production maximization followed by minimization of  total flux. This is already very useful. It would be great if optimization can be more flexible for users.

**Comment by dukovski** [comment]
We do have the possibility to run several optimizations. We don't have it fully supported by cometspy yet though. If interested we can implement it, and you are welcome to join the development.  Thanks!
